### ISSUE TITLE
Fix custom_profile test case

### ISSUE THREAD

**Issue by tracywalker** [mozilla/iris#1104] opened 2018-09-11 17:08 UTC
experiments/custom_profile is failing consistently on Windows. Please investigate and fix this failing test.

**Comment by IonutBudeanu** [comment] 2018-09-18 13:26
Cannot reproduce on my machine.

The test has been PASSED 12 out of 12 times.

**Comment by IonutBudeanu** [comment] 2018-09-20 13:55
Closing the issue based on the above comment.

**Closed** 2018-09-20 13:55 UTC
Labels: test case
