### ISSUE TITLE
Linux: Errors when installing pip libraries via setup

### ISSUE THREAD

**Issue by mwobensmith** [mozilla/iris#71] opened 2018-04-25 11:46 UTC
When invoking `pip install -e . `to run the `setup.py` file, we get an error that `pyautogui` can't find `xlib`. However, we have already specified `xlib` in the setup file, so it should be available.

The workaround is to install `xlib` via `pip install xlib` before running `pip install -e .`, but we'd like to not have to do this.

**Comment by mwobensmith** [comment] 2018-04-26 08:44
I may have fixed this but need to keystroke it again on a clean image to make sure.

**Comment by mwobensmith** [comment] 2018-04-26 08:56
Note: remove commented lines in `setup.py` when complete.

**Comment by mwobensmith** [comment] 2018-07-14 00:23
The current solution is to install xlib in the bootstrap script instead of Python setup. This works but I want to investigate a real fix.

**Comment by AndreiH** [comment] 2018-09-20 15:21
This is resolved by bumping up PyAutoGUI version, since it was an issue of incompatibility.
The issue is ready for review under branch "issue_71". That branch will also resolve issue https://github.com/mozilla/iris/issues/72
I have tested this on different virtualenvS and run the test suite.
Please review @mwobensmith . Thanks !

**Closed** 2018-09-21 22:47 UTC
Labels: core
