### ISSUE TITLE
Error while setting up the project

### ISSUE THREAD

**Issue by navgurukul-shivani18** [mozilla/iris#1304] opened 2018-10-14 13:09 UTC
I want to participate in this project in this outreachy round , i am trying to setup this project from yesterday on different Linux OS , but not getting any lead. Every time i get some weird error. Currently I am trying to setup `iris` on Debian/Ubuntu Linux and while running the last command `iris` in NUM Lock off condition i am getting this error 

```
(iris) championshuttler@debian:~/Desktop/Shivani/iris$ iris
Traceback (most recent call last):
  File "/home/championshuttler/.local/share/virtualenvs/iris-QASWKkKC/bin/iris", line 11, in <module>
    load_entry_point('iris', 'console_scripts', 'iris')()
  File "/home/championshuttler/Desktop/Shivani/iris/iris/__main__.py", line 46, in main
    Iris()
  File "/home/championshuttler/Desktop/Shivani/iris/iris/__main__.py", line 57, in __init__
    if self.control_center():
  File "/home/championshuttler/Desktop/Shivani/iris/iris/__main__.py", line 110, in control_center
    launch_firefox(fx_path, profile=profile_path, url=self.base_local_web_url)
  File "/home/championshuttler/Desktop/Shivani/iris/iris/api/helpers/general.py", line 48, in launch_firefox
    subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 390, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1024, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```
Can you please help me @mwobensmith please?

Thanks

**Comment by navgurukul-shivani18** [comment] 2018-10-14 14:03
Hi @mwobensmith we are getting another error as well . while trying to setup the project , this project is erasing all the directories from the laptop , and it happened with 3 laptop of my friends, 2 of them were using Ubuntu and one using Mint Linux OS, when we restart our laptop all the directories from our laptop got removed .

Can you help me what to do please?

**Comment by mwobensmith** [comment] 2018-10-15 17:09
Hi @navgurukul-shivani18, regarding the first issue, it is new to me and I'm not sure what's happening. If you still see this, try to run Iris with the additional `-i DEBUG` flag, which will capture more information that might help us.

Regarding the second issue, are you saying that Iris erases all content from the hard drive? I'm not sure I understand. Obviously it can't be erasing everything, or you wouldn't be able to restart. :) 

> while trying to setup the project , this project is erasing all the directories from the laptop 

Can you be more specific? At what exact point during setup do you see this?

For what it's worth, we only support Ubuntu Linux right now. All of us on the team here are using this, and we haven't seen this problem, so I am interested to understand what is happening.

**Comment by navgurukul-shivani18** [comment] 2018-10-15 17:40
After running `iris -i DEBUG` I am getting this error 
```
iris -i DEBUG
No handlers could be found for logger "iris.api.core.pattern"
Traceback (most recent call last):
  File "/usr/local/bin/iris", line 11, in <module>
    load_entry_point('iris==1.0', 'console_scripts', 'iris')()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 484, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2714, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2332, in load
    return self.resolve()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2338, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/dist-packages/iris-1.0-py2.7.egg/iris/__main__.py", line 25, in <module>
    from api.helpers.general import launch_firefox, quit_firefox, get_firefox_channel, get_firefox_version, \
  File "/usr/local/lib/python2.7/dist-packages/iris-1.0-py2.7.egg/iris/api/helpers/general.py", line 10, in <module>
    from iris.api.core.firefox_ui.menus import LibraryMenu
  File "/usr/local/lib/python2.7/dist-packages/iris-1.0-py2.7.egg/iris/api/core/firefox_ui/menus.py", line 8, in <module>
    class LibraryMenu(object):
  File "/usr/local/lib/python2.7/dist-packages/iris-1.0-py2.7.egg/iris/api/core/firefox_ui/menus.py", line 9, in LibraryMenu
    BOOKMARKS_OPTION = Pattern('library_menu_bookmarks_option.png')
  File "/usr/local/lib/python2.7/dist-packages/iris-1.0-py2.7.egg/iris/api/core/pattern.py", line 94, in __init__
    path = _get_image_path(inspect.stack()[1][1], image_name)
  File "/usr/local/lib/python2.7/dist-packages/iris-1.0-py2.7.egg/iris/api/core/pattern.py", line 257, in _get_image_path
    raise FindError('Pattern not found.')
iris.api.core.errors.FindError: Pattern not found.
```
### Second Issue 

Actually after installing the project or trying to run the project , it moves `home/<username>` to `/usr/local/share/testdata`

I setup the project on my laptop friend yesterday successfully although.

I mailed you @mwobensmith can you please check it out :)

Also is there any `IRC` channel to ask doubts?

**Comment by mwobensmith** [comment] 2018-10-15 18:02
Yikes, well, there appears to be two issues here, both need exploration.

One, it looks like a runtime error is preventing Iris from getting any further. We can look into that.

Two, moving your local user folder to another location. 😱 Definitely don't want to do that. Investigating that also.

**Comment by navgurukul-shivani18** [comment] 2018-10-15 18:09
@mwobensmith for second issue i am sharing some info here how did i move the directories back to original locations. If some one else faces same issues in future he/she might get look at it :)


![image](https://user-images.githubusercontent.com/40683717/46969385-82723600-d0d3-11e8-8452-da91b446bb01.png)

**Comment by mwobensmith** [comment] 2018-10-15 22:36
The error above could have been caused by line 99 in the linux_bootstrap.sh script. 
`sudo mv * /usr/local/share/tessdata/`

For that to have happened, the previous lines would have to have failed somehow. We'll look into it.

**Comment by mwobensmith** [comment] 2018-10-15 22:40
@AndreiH Do you think that there's something we can do in the `linux_bootstrap.sh` script, prior to line 98, to make sure the Tesseract file has been properly downloaded and unzipped? I'm trying to understand how the above error could have happened.

**Comment by wizofe** [comment] 2018-10-16 01:35
@mwobensmith That could be avoided by checking if `tesseract.exe` is installed otherwise it wouldn't perform the `mv *`?

Something like:

```bash
command -v tesseract.exe >/dev/null 2>&1 || { echo >&2 "Tesseract is not installed. Exiting!"; exit 1; }
```

I can do a PR if that makes sense to you!

**Comment by mwobensmith** [comment] 2018-10-16 01:53
Hi @wizofe, that is a possibility, but I want to wait to see what @AndreiH thinks, since he wrote some of these scripts and this is something we are actively investigating. We will call on you if we need some assistance here. 😊

**Comment by AndreiH** [comment] 2018-10-16 08:38
Yikes, that is not good. Thanks for opening this guys !
It seems that the `tessdata` for tesseract download failed, or the extraction failed.
We were definitely planning to add more checks and verifications in the `Bootstrap` scripts, but seeing this issue, now we have to do this as a priority.

Yes @mwobensmith more secure checks will be added to make sure that this won't happen again.
We can add a check for the file completely downloading and that it has been correctly extracted and that `cd` is the correct path.  Only after we are in the correct path we can move the `tessdata`.

I will start working on this

**Comment by alejo4373** [comment] 2018-10-16 13:03
Hi guys, I'm an [Outreachy](https://www.outreachy.org/december-2018-march-2019-outreachy-internships/communities/mozilla/#uiux-web-design-for-a-new-mozilla-automation-proje) applicant as well. I'm a JavaScript developer really interested in Python and Gnu/Linux. I was wondering if I could help by writing a shell script for Debian based distros that checks for the dependencies before trying to install them. I personally think a script shouldn't be executing commands with sudo, maybe the script could output a line like Please run: `$> sudo apt-get install scrot libcairo2-dev ...` with the dependencies that are not installed in the system. This seems like a really interesting project please let me know if I can help in any other way. Thank you!

**Comment by alejo4373** [comment] 2018-10-16 15:07
@AndreiH & @mwobensmith  As noted in the [Taceback](https://github.com/mozilla/iris/issues/1304#issue-369900806), [iris/\_\_main\_\_.py](https://github.com/mozilla/iris/blob/master/iris/__main__.py#L110) calls `launch_firefox`. The problem is that [fx_path](https://github.com/mozilla/iris/blob/c7f0c2ff10229c6cff5bd2b4d58fb3468cd01ad1/iris/__main__.py#L108) which is passed to `launch_firefox` is set to `'/usr/lib/firefox/firefox'` in [line 108](https://github.com/mozilla/iris/blob/c7f0c2ff10229c6cff5bd2b4d58fb3468cd01ad1/iris/__main__.py#L108) when in Debian based system the firefox executable will be in `'/usr/bin/firefox'`. Once I changed it to point to the correct `firefox`, iris launched as normal.

**Comment by championshuttler** [comment] 2018-10-16 15:10
Hi @alejo4373 which Debian based Os you are using?

**Comment by alejo4373** [comment] 2018-10-16 15:11
> Hi @alejo4373 which Debian based Os you are using?

Debian 9.5 stretch / x86_64 Linux 4.9.0-8-amd64

**Comment by alejo4373** [comment] 2018-10-16 15:29
I understand that Ubuntu puts a `firefox` executable in `/usr/lib/firefox/firefox`, but it also puts on in `/usr/bin/firefox` as seen [here](https://packages.ubuntu.com/bionic/amd64/firefox/filelist). I believe `/usr/bin/firefox` is the recommended one to run though since its the same for [Ubuntu](https://packages.ubuntu.com/bionic/amd64/firefox/filelist) and [Debian](https://packages.debian.org/stretch/amd64/firefox-esr/filelist). Would be happy to send a PR with the change.

**Comment by alejo4373** [comment] 2018-10-17 04:29
@mwobensmith I'm glad the issue is fixed. I understand what you are saying about this project working now and in the future regarding Debian. Is there anything else I can help with? I came here because a project titled `UI/UX web design for a new Mozilla automation project`[here in Outreachy](https://www.outreachy.org/apply/project-selection/). I am really interested in participating and I think I meet the requirements, please let me know how I can help. Thank you.

**Comment by AndreiH** [comment] 2018-10-17 12:37
Hello @mwobensmith !
This is now ready for review on branch `issue_1304` https://github.com/mozilla/iris/compare/dev...issue_1304
All 3 bootstraps were updated with verifications/checks and skips if something already installed or present on the System.
They were tested on all three Environments (Windows, Linux and OSX) on clean VMs.

Thanks !

**Comment by mwobensmith** [comment] 2018-10-17 13:39
@alejo4373 Thanks for your interest. I won't spend too much time in this Git issue answering that specific question, but there is a link on that page to our IRC channel to discuss the project. So, with regards to Outreachy, that's a good place to take the conversation.

Regarding the rest of the project, we are getting close to going live and will soon be in a better state to solicit contributions in general. So, your help there is also welcome. Stay tuned for better documentation in the next 1-2 weeks. 🙂

**Closed** 2018-10-19 17:56 UTC
