### ISSUE TITLE
Investigate build version difference in update test

### ISSUE THREAD

**Issue by mwobensmith** [mozilla/iris#1643] opened 2018-12-05 20:12 UTC
From Cornel in Release QA:

> We noticed that at the end of an update test, iris visually shows in About window an incorrect build version (we expected to see 64.0b14 and got 64.0b13), even though in CMD the tests correctly displayed the target version 64.0b14.
> manual_update - only localized builds 
> background_update - all languages have this issue (including en-US).

Does this mean that the test should fail? Or is it a Firefox bug?

**Comment by ashughes1** [comment] 2019-03-11 20:39
I'm going to close this since nobody has been able to reproduce it as of yet. Please reopen if it becomes reproducible.

**Comment by ashughes1** [comment] 2019-03-20 21:07
Both Tracy and I encountered this issue today intermittently while testing the update script. We can both confirm that when the issue occurs we are updating to the correct version but for some reason the test logic is expecting a different version than what we get. In today's example Firefox 64.0b10 updates to 67.0b3, as it expects to before Firefox is restarted. However after the restart the test expects 66.0 and fails.

Here is sample output:
```
Starting BACKGROUND update test: 

LOCALE = de
FIREFOX VERSION = 66.0b10
CHANNEL = beta


2019-03-20 12:35:55 [INFO] [iris.local_web_server] Serving HTTP on 127.0.0.1 port 2000.
2019-03-20 12:35:55 [INFO] [mozdownload.scraper] Retrieving list of candidate builds from https://archive.mozilla.org/pub/firefox/candidates/66.0b10-candidates/
2019-03-20 12:35:55 [INFO] [mozdownload.scraper] Found 1 build: build1
2019-03-20 12:35:55 [INFO] [mozdownload.scraper] Selected build: build1
2019-03-20 12:35:55 [INFO] [mozdownload.scraper] File has already been downloaded: /Users/iris/.iris/cache/firefox-66.0b10-build1.de.mac.dmg
2019-03-20 12:36:06 [INFO] [mozdownload.scraper] Retrieving list of candidate builds from https://archive.mozilla.org/pub/firefox/candidates/67.0b3-candidates/
2019-03-20 12:36:06 [INFO] [mozdownload.scraper] Found 1 build: build1
2019-03-20 12:36:06 [INFO] [mozdownload.scraper] Selected build: build1
2019-03-20 12:36:06 [INFO] [iris.firefox.firefox_app] Latest available version for beta channel is: 67.0b3
2019-03-20 12:36:06 [INFO] [iris.test_runner] Running tests
2019-03-20 12:36:06 [INFO] [iris.test_runner] 
------------------------------------------------------------------------------------------------------------------------
2019-03-20 12:36:06 [INFO] [iris.test_runner] Executing: 1 - [background_update]: This is a test for Firefox background update.
2019-03-20 12:36:11 [SUCCESS] [iris.test_case] >>> PASSED <<< Step 1: Firefox version is correct (66.0b10)
2019-03-20 12:36:11 [INFO] [iris.test_case] Current version: 66.0b10, updating to version: 67.0b3.
2019-03-20 12:37:28 [WARNING] [iris.test_case] >>> FAILED <<< Step 2: Firefox successfully updated from 66.0b10 to 67.0b3. - [Actual]: 67.0b3 [Expected]: 66.0 

------------------------------------------------------------------------------------------------------------
>> Traceback (most recent call last):                                                                     <<
>>   File "/Users/iris/.local/share/virtualenvs/iris-FrnbsRKg/bin/iris", line 11, in <module>             <<
>>     load_entry_point('iris', 'console_scripts', 'iris')()                                              <<
>>   File "/Users/iris/Development/iris/iris/__main__.py", line 38, in main                               <<
>>     run_iris()                                                                                         <<
>>   File "/Users/iris/Development/iris/iris/__main__.py", line 108, in run_iris                          <<
>>     run(master_test_list, tests, browser)                                                              <<
>>   File "/Users/iris/Development/iris/iris/test_runner.py", line 69, in run                             <<
>>     current.run()                                                                                      <<
>>   File "/Users/iris/Development/iris/iris/tests/update/background_update.py", line 67, in run          <<
>>     'Firefox successfully updated from %s to %s.' % (current_version, update_step))                    <<
>>   File "/Users/iris/Development/iris/iris/asserts.py", line 49, in assert_contains                     <<
>>     Result('FAILED', message, actual, expected, print_error(format_stack(traceback.extract_stack())))) <<
------------------------------------------------------------------------------------------------------------

2019-03-20 12:37:30 [INFO] [iris.api.helpers.results] [background_update] - >>> FAILED <<< (Finished in 82.72 second(s))
```

**Comment by ashughes1** [comment] 2019-03-20 22:14
After a lot of debugging and manual testing I have been able to reproduce this with manual steps to reproduce (no Iris involved).

1. Installed Firefox 64.0b10 ro
2. Check for update, download update and restart
3. When Firefox reloads go to about:support > got Firefox 66.0 Release on the beta channel
4. Check for update, download update and restart again
5. When Firefox reloads go to about:support > got Firefox 67.0b3 Beta on the beta channel

This happens intermittently as sometimes it goes straight to 67.0b3 as expected, but it seems like under some circumstances (perhaps a server-side race condition) we get the latest RC on the beta channel instead of the latest Beta.

I'll do some more debugging and file a Firefox bug.

**Comment by ashughes1** [comment] 2019-03-20 22:32
Filed [bug 1537591](https://bugzilla.mozilla.org/show_bug.cgi?id=1537591).

**Comment by tracywalker** [comment] 2019-03-21 14:20
This now begs the question if this is the correct way to determine what the "expected" build is.  It's possible the update system will break down by updating to an incorrect build. For example, in the case we were investigating yesterday, what if Firefox actually updates to 66.0. The Iris update test would confirm 66.0 is the correct build, a false PASS. It might be better if the bash script accepted a parameter, say --expected '<build>'. Then the script could pass that expected build version into the Iris update tests.  The tester controls the expected build instead of programmatically fetching the expected build from an unreliable source that could lead to false PASS results.

**Comment by tracywalker** [comment] 2019-03-21 14:28
in order for us to deploy to release QA, we will need something like the above suggestion as a work around for the Firefox/Server bug.

**Comment by ashughes1** [comment] 2019-03-22 21:52
I saw Chris Atlee's comment on the bug that this is expected behaviour when update throttling is enabled on the AUS server. Basically when throttling is at 50% half the pings will get Beta and half will get RC. I'm not sure how we can work around this in automation and "guess" which build we should be getting in a reliable way.

**Comment by mwobensmith** [comment] 2019-03-22 22:29
How would we work around this in a manual test scenario? If we're supposed to look for two potential outcomes, I guess that could be verified programmatically as well.

**Comment by catlee** [comment] 2019-03-27 15:03
I'm not sure what the right approach is here either. I can point you at some data sources to help determine what releases are active though!

https://product-details.mozilla.org/1.0/ has a list of shipped releases
https://aus-api.mozilla.org/api/v1/releases has list of all releases balrog knows about
https://aus-api.mozilla.org/api/v1/rules describes the currently active rules

You can combine the rule/release information from Balrog to determine what releases should be live. e.g.
https://aus-api.mozilla.org/api/v1/rules/firefox-release will give you information about the current firefox release rule.

**Comment by tracywalker** [comment] 2019-03-27 16:20
Chris, with the information you have given, maybe the Iris team can come up with an elegant automation solution. For now, given that the updates to the first Beta are throttled, we have decided to recommend to Release QA to not run Iris update tests against Beta until the throttling period is complete.  I think they may have already been avoiding manually running update tests on the first betas to avoid throttling too.

**Comment by MarisBogdan** [comment] 2019-03-28 14:03
When the updates are let's say at 50%, and this happens only with **release** update channel we can't test background updates since we will fall on one of the sides (receiving the latests or not). For manual testing we are using this pref (_app.update.auto_ set to _false_) to stop Fx downloading the update in the background. This way we will always get the latest build available.

**Comment by catlee** [comment] 2019-03-28 14:50
I believe that you can pass ?force=-1 to get the fallback update.

**Comment by tracywalker** [comment] 2019-04-25 14:52
We understand the problem here now.  QA team should do early, throttled beta update testing manually.  Once throttle is set to 100%, they can then run Iris update tests for the remainder of the beta cycle.

**Closed by tracywalker** 2019-04-25 14:52 UTC
Labels: fx-bug
