### ISSUE TITLE
Fix copy_history_time_range_paste_it_bookmark_toolbar test

### ISSUE THREAD

**Issue by spronoza** [mozilla/iris#2898] opened 2019-04-18 13:43 UTC
The test fails at step: "019-04-17 13:16:46,355 [ERROR] [iris.test_case] >>> ERROR <<< Error encountered in test" for OSX

**Comment by tracywalker** [comment] 2019-04-19 13:11
This was already filed as issue #2851.  Please check for existing duplicates before filing new issues. 

I am going to mark the original a duplicate of this. since that issue says it cannot reproduce and this one say the test fails.

**Closed** 2019-04-19 15:25 UTC
