### ISSUE TITLE
Iris2 setup issues

### ISSUE THREAD

**Issue by paulprokhorovmoz** [mozilla/iris#198] opened 2019-05-06 16:35 UTC
After setup using bootstrap scripts and running the "iris -k" command I get following error messages:

**Linux**

`Traceback (most recent call last):
  File "/home/user/.local/share/virtualenvs/iris2-BjfJp2OK/bin/iris", line 11, in <module>
    load_entry_point('iris2', 'console_scripts', 'iris')()
  File "/home/user/.local/share/virtualenvs/iris2-BjfJp2OK/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/user/.local/share/virtualenvs/iris2-BjfJp2OK/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2843, in load_entry_point
    return ep.load()
  File "/home/user/.local/share/virtualenvs/iris2-BjfJp2OK/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2434, in load
    return self.resolve()
  File "/home/user/.local/share/virtualenvs/iris2-BjfJp2OK/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2440, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/user/iris2/src/__main__.py", line 16, in <module>
    from src.configuration.config_parser import validate_config_ini
  File "/home/user/iris2/src/configuration/config_parser.py", line 8, in <module>
    from configparser import ConfigParser
ImportError: No module named configparser`

**Win 10** 

`[Bugzilla] section has properties with no values: [api_key]. Tests blocked by Bugzilla issues will be automatically skipped.
[GitHub] section has properties with no values: [github_key]. Tests blocked by GitHub issues will be automatically skipped.
Traceback (most recent call last):
  File "c:\users\prokhorov\.virtualenvs\iris2-azvl-ibu\lib\site-packages\mozrunner\base\runner.py", line 136, in start
    process.run(self.timeout, self.output_timeout)
  File "c:\users\prokhorov\.virtualenvs\iris2-azvl-ibu\lib\site-packages\mozprocess\processhandler.py", line 785, in run
    self.proc = self.Process([self.cmd] + self.args, **args)
  File "c:\users\prokhorov\.virtualenvs\iris2-azvl-ibu\lib\site-packages\mozprocess\processhandler.py", line 123, in __init__
    universal_newlines, startupinfo, creationflags)
  File "c:\users\prokhorov\appdata\local\programs\python\python37\Lib\subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "c:\users\prokhorov\.virtualenvs\iris2-azvl-ibu\lib\site-packages\mozprocess\processhandler.py", line 309, in _execute_child
    winprocess.EnvironmentBlock(env),
  File "c:\users\prokhorov\.virtualenvs\iris2-azvl-ibu\lib\site-packages\mozprocess\winprocess.py", line 167, in __init__
    self._as_parameter_ = LPCWSTR("\0".join(values))
ValueError: embedded null character`

`During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "C:\Users\prokhorov\.virtualenvs\iris2-AzvL-Ibu\Scripts\iris-script.py", line 11, in <module>
    load_entry_point('iris2', 'console_scripts', 'iris')()
  File "c:\users\prokhorov\iris2\src\__main__.py", line 44, in main
    user_result = launch_control_center()
  File "c:\users\prokhorov\iris2\src\__main__.py", line 189, in launch_control_center
    fx_runner.start()
  File "c:\users\prokhorov\.virtualenvs\iris2-azvl-ibu\lib\site-packages\mozrunner\base\browser.py", line 85, in start
    BaseRunner.start(self, *args, **kwargs)
  File "c:\users\prokhorov\.virtualenvs\iris2-azvl-ibu\lib\site-packages\mozrunner\base\runner.py", line 141, in start
    reraise(RunnerNotStartedError, "Failed to start the process: %s" % value, tb)
  File "c:\users\prokhorov\.virtualenvs\iris2-azvl-ibu\lib\site-packages\six.py", line 691, in reraise
    if value.__traceback__ is not tb:
AttributeError: 'str' object has no attribute '__traceback__'
Exception ignored in: <function BaseProfile.__del__ at 0x00000284E7CAE730>
Traceback (most recent call last):
  File "c:\users\prokhorov\.virtualenvs\iris2-azvl-ibu\lib\site-packages\mozprofile\profile.py", line 76, in __del__
  File "c:\users\prokhorov\.virtualenvs\iris2-azvl-ibu\lib\site-packages\mozprofile\profile.py", line 258, in cleanup
  File "c:\users\prokhorov\.virtualenvs\iris2-azvl-ibu\lib\site-packages\mozprofile\profile.py", line 272, in clean_preferences
  File "c:\users\prokhorov\.virtualenvs\iris2-azvl-ibu\lib\site-packages\mozprofile\profile.py", line 321, in pop_preferences
NameError: name 'open' is not defined
Exception ignored in: <function ProcessHandlerMixin.Process.__del__ at 0x00000284E7D1A598>
Traceback (most recent call last):
  File "c:\users\prokhorov\.virtualenvs\iris2-azvl-ibu\lib\site-packages\mozprocess\processhandler.py", line 143, in __del__
AttributeError: 'Process' object has no attribute '_job'`

**Comment by paulprokhorovmoz** [comment] 2019-05-06 16:38
I tried to setup it using code from the dev branch.

**Comment by mwobensmith** [comment] 2019-05-06 16:39
@mariusandreifilip Can you work with him to figure out where these errors are coming from? Start with the first error and suggest a few things he can try, and you two can go back and forth until the issue is resolved. Please update this Git issue with what you find so that we can track the work to fix these in Iris. I suspect there is more than one bug here, and not necessarily in the bootstrap scripts.

**Comment by mwobensmith** [comment] 2019-05-06 16:44
@paulprokhorovmoz I am curious about the first error on Linux. When you created the `pipenv install` environment, were you in the Iris root? Or were you in the bootstrap folder? I am wondering if we are starting in the wrong folder and can't see the project root from there.

**Comment by paulprokhorovmoz** [comment] 2019-05-07 08:19
@mwobensmith I followed the instructions and ran `pipenv install` from root. The only difference that I made was permissions changing to `-rwxrwxrwx` for linux_bootstrap.sh file.

**Comment by mariusandreifilip** [comment] 2019-05-07 13:35
**Ubuntu 16.04 Update :**
1.We have to delete the actual virtual environments that we have in order to run iris 2 please look in your logs 

"/home/user/.local/share/virtualenvs/iris2-BjfJp2OK/local/lib/**python2.7**/site-packages/pkg_resources/


2.There are a couple of missing packages that we need to install on the system
**sudo apt-get install python3.7-dev --required for python headers**
**sudo apt-get install python-psutil --required for the psutil library**

3.There is a bug in the latest pytest that creates an incompatibility with more-itertools library so to fix this will have to install an older version
 **pip install more-itertools==5.0.0**


All of this will be part of the bootstrap in the future but until Roxana finishes them we can do it manually with the above commands

**Closed** 2022-02-28 15:48 UTC
Labels: Type: Bug, ARCHIVED
