### ISSUE TITLE
Fix restart_browser test on Mac

### ISSUE THREAD

**Issue by silviuFlorin** [mozilla/iris#618] opened 2018-06-11 14:32 UTC
Investigate and fix restart_browser test on Mac

**Comment by mwobensmith** [comment] 2018-06-12 18:33
What is the error?

**Comment by icrisan** [comment] 2018-06-14 09:11
[restart_browser]: This is a test case that restarts the browser
2018-06-14 11:06:12 [WARNING] [iris.api.helpers.results] Step: Find Google search image, outcome: >>> FAILED <<< 

------------------------------------------------------------------------------------------------------------------------
» Traceback (most recent call last):                                                                                   «
»   File "/Users/ioanacrisan/iris/venv/bin/iris", line 11, in <module>                                                 «
»     load_entry_point('iris', 'console_scripts', 'iris')()                                                            «
»   File "/Users/ioanacrisan/iris/iris/__main__.py", line 37, in main                                                  «
»     Iris()                                                                                                           «
»   File "/Users/ioanacrisan/iris/iris/__main__.py", line 51, in __init__                                              «
»     test_runner.run(self)                                                                                            «
»   File "/Users/ioanacrisan/iris/iris/test_runner.py", line 59, in run                                                «
»     current.run()                                                                                                    «
»   File "/Users/ioanacrisan/iris/iris/tests/experiments/restart_browser.py", line 30, in run                          «
»     assert_true(self, expected_1, 'Find Google search image')                                                        «
»   File "/Users/ioanacrisan/iris/iris/asserts.py", line 31, in assert_true                                            «
»     assert_equal(test_case, actual, True, message)                                                                   «
»   File "/Users/ioanacrisan/iris/iris/asserts.py", line 26, in assert_equal                                           «
»     test_case.add_results('FAILED', message, actual, expected, print_error(format_stack(traceback.extract_stack()))) «
------------------------------------------------------------------------------------------------------------------------

**Comment by icrisan** [comment] 2018-09-18 09:03
Could not reproduce this issue anymore. Tried more than 30 times. Closing bug.

**Comment by icrisan** [comment] 2018-09-21 08:52
Updated test to use local sites. @tracywalker please review. Thank you!

**Comment by tracywalker** [comment] 2018-09-21 16:12
code approved

**Closed** 2018-09-21 22:47 UTC
Labels: bug, test case
