### ISSUE TITLE
Test 'clear_history' intermittently failing

### ISSUE THREAD

**Issue by mwobensmith** [mozilla/iris#534] opened 2018-05-29 18:09 UTC
Windows only.

@mariusandreifilip I created the test, but you are able to see the failure. Can you copy/paste the error for the test here?

**Comment by mariusandreifilip** [comment] 2018-05-31 14:36
The issue here Matt is the clear_recent_history() method and when we run 2 modifier and a text it seems that pyautoguy is pressing only one modifier and I don't know the exact reason.As a consequence i refactored the test to use images.The branch is andrei/issue_534 please let me know if is an agreed fix.

**Comment by mwobensmith** [comment] 2018-05-31 18:06
If `pyautogui` is truly only pressing one modifier instead of two, then we need to fix that and not work around it in this test case. 

Run `iris -t clear_history -i DEBUG`  and when it calls `clear_recent_history`, there will be debug output indicating what keys were pressed. Copy and paste that output into this page.

**Comment by mariusandreifilip** [comment] 2018-06-04 13:52
iris -t clear_history -i DEBUG is not relevant because it prints only the method arguments to console.The pyautogui,hotkey() returns none and we don't know what is pressed.After a hole day of forums I finally found the problem,it seems that when NumLock is pressed Delete is disabled and vice versa so the solution here is to deactivate NumLock.I guess that my branch can be ignored in this case :D since the test runs without NumLock activated.Should I create a task for NumLock disable and work on it?

**Comment by mwobensmith** [comment] 2018-06-04 15:49
So, to paraphrase, if `Key.NUM_LOCK` is on, then `Key.DELETE` is ignored. Is that correct? Does that mean `Key.CTRL` and `Key.SHIFT` are also ignored? Other keys as well?

Should Iris require that `Key.NUM_LOCK` be turned off before a test is run?

We have #301 open to implement `Key.isLockOn`. It is not an easy task, as it will require different implementations on all three platforms. However, if we had it, and if the above assumptions were true, we could then check `Key.isLockOn(Key.NUM_LOCK)` when Iris starts and abort if it's locked.

> Should I create a task for NumLock disable

Are you saying that you are able to turn off `Key.NUM_LOCK` programmatically?

**Comment by mariusandreifilip** [comment] 2018-06-04 20:20
Yes your correct, when Key.NUM_LOCK is on Key.DELETE is ignored.What I tested so far only Key.DELETE is ignored and all the combinations that involves DELETE(Ex:Ctrl+Alt+Delete,Ctr+Shift+Delete..).I can take that task is not very difficult to implement it at least for Windows I already have a working solution:
//def get_Key_State(key):
    state= windll.GetKeyState(key)
.......................
#it returns 0 for Key,off and 1 for Key.on

for Linux we can do something like this:
xset -q | grep Caps
    00: Caps Lock:   off    01: Num Lock:    on     02: Scroll Lock: off 

for Osx I don't have a solution at this point

Are you saying that you are able to turn off Key.NUM_LOCK programmatically?
For windows I think that is possible using the native User32.dll

**Comment by mwobensmith** [comment] 2018-06-04 23:07
OK, thanks for the info. Whatever solution we implement, we have to make it work the same on all three platforms.

We would call `Key.isLockOn(Key.NUM_LOCK)`, and quit Iris if it returns `True`.

To move forward, we need to know how to do this on Mac.

**Comment by mwobensmith** [comment] 2018-06-08 18:29
This will be fixed by #592.

**Comment by mwobensmith** [comment] 2018-06-09 01:04
Actually, it appears to be broken again, but for a different reason.

@mariusandreifilip - you may have forgotten to include a new image on Mac. Take a look.

**Comment by mariusandreifilip** [comment] 2018-06-11 11:10
created branch issue_534 please review

**Comment by silviuFlorin** [comment] 2018-06-11 11:16
Code approved

**Comment by mariusandreifilip** [comment] 2018-06-17 17:01
@tracywalker can you please provide logs for this fail because I cannot reproduce this even in full run

**Comment by tracywalker** [comment] 2018-06-18 13:49
@silviuFlorin,  I only saw it during a full run and only once.  May have been some networking issue as I was testing on guest network at the hotel.  Let's keep an eye out to see if it fails again.  Close this issue in a week, if there are no new reports.

**Closed** 2018-06-23 00:45 UTC
Labels: bug
