### ISSUE TITLE
'Failed loading language \'eng\' Tesseract couldn\'t load any languages! Could not initialize tesseract.' error when running bootstrap on WIN7

### ISSUE THREAD

**Issue by icrisan** [mozilla/iris#2864] opened 2019-04-15 13:48 UTC
After running bootrstrap on WIN7 the following error is thrown when running test cases that use OCR. I've found this issue after I've run test case "clear_download_preview_panel" from my branch "issue_2610".

File "c:\users\ioana.crisan\.virtualenvs\iris-dk9j7qqa\lib\site-packages\pytessera
ct\pytesseract.py", line 178, in run_tesseract
    raise TesseractError(status_code, get_errors(error_string))
pytesseract.pytesseract.TesseractError: (1, u'Error opening data file C:\\Users\
\ioana.crisan\\scoop\\apps\\tesseract\\current/tessdata/eng.traineddata Please make
sure the TESSDATA_PREFIX environment variable is set to the parent directory of
your "tessdata" directory. Failed loading language \'eng\' Tesseract couldn\'t l
oad any languages! Could not initialize tesseract.')
Process Process-1:
Traceback (most recent call last):
  File "C:\Python27\Lib\multiprocessing\process.py", line 267, in _bootstrap
    self.run()
  File "C:\Python27\Lib\multiprocessing\process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "c:\users\ioana.crisan\iris\iris\local_web_server.py", line 127, in _init_
    self.start()
  File "c:\users\ioana.crisan\iris\iris\local_web_server.py", line 146, in start
    httpd.handle_request()
  File "C:\Python27\Lib\SocketServer.py", line 271, in handle_request
    fd_sets = _eintr_retry(select.select, [self], [], [], timeout)
  File "C:\Python27\Lib\SocketServer.py", line 150, in _eintr_retry
    return func(*args)
KeyboardInterrupt

**Comment by mwobensmith** [comment] 2019-04-15 22:00
My Windows 7 environment can't run the bootstrap at all, which has been a problem for me for a long time. So, I'm not able to test right now.

Is this a new problem? Does it happen with the old script, before your changes were added?

**Comment by icrisan** [comment] 2019-04-16 07:13
This is a new problem. The changes that I've added to the bootstrap are placed at the end, after all the dependencies are installed and does not cause this error.

**Comment by tracywalker** [comment] 2019-04-16 13:50
I discussed this with Ioana this morning.  The problem is not specific to her changes. Anyone that runs the bootstrap on dev with Win7 will get updated such that any test that uses ocr will fail.

Fro now DO NOT run bootstrap on Win7.  We're going to suggest  a workaround on individual Win7 machines, while this issue is being investigated.  Baring any other issue with the download manager work, look for an email explaining what to do later this week.

**Comment by tracywalker** [comment] 2019-04-16 16:30
Exalt team ,when you're investigating this, please work with Roxana as she is also working on the bootstrap and encountering issues on win7 in Iris2.  Just so you all don't duplicate efforts.

**Comment by mwobensmith** [comment] 2019-04-17 17:51
After discussion with @mariusandreifilip it appears that the issue is that latest Python 2.7.16 breaks Tesseract. Coincidentally, we are already working on Python downgrading in Iris 2.0, so the same logic can be used to address this issue as well.

Assigning to @rrobotin since she's handling all of the other bootstrap work at the moment.

**Comment by paulprokhorovmoz** [comment] 2019-04-18 15:24
I've got the this issue on Win 10 using Python 2.7.15 , so probably the latest version of interpreter isn't a root cause of a problem.

**Comment by paulprokhorovmoz** [comment] 2019-04-18 15:27
It might be obvious, but as a quick and dirty fix for the particular machine we can use this approach
https://stackoverflow.com/a/22801937

**Comment by tracywalker** [comment] 2019-04-19 16:12
> It might be obvious, but as a quick and dirty fix for the particular machine we can use this approach
> https://stackoverflow.com/a/22801937

That's a reasonable for a short term workaround.  But we need a general solution that can be implemented in the bootstrap. So this doens't have to be addressed from one machine to the next.

**Closed** 2019-04-29 16:03 UTC
Labels: bug

**Comment by AmbarishGK** [comment] 2019-05-28 09:35
I get this error. What is the problem?
![tesse](https://user-images.githubusercontent.com/23191860/58467849-0906ef80-815a-11e9-8c06-743682843a04.png)

**Comment by pavelciapa** [comment] 2019-05-28 10:26
> 
> 
> I get this error. What is the problem?
> ![tesse](https://user-images.githubusercontent.com/23191860/58467849-0906ef80-815a-11e9-8c06-743682843a04.png)

Error with **tesseract** often indicates that bootstrap install was not finished correctly. Cloning Iris1 again and installing bootstrap can help. Note that adding missing language pack to **tesseract**  plugin folder can fix error, but looks like your issue is not about that. 

Also I see that error is rising from `/.virtualenvs/..../python3.6/` , that seems that virt env is using Python 3+ version, but for Iris1 correct is Python 2.7+. And Iris1 is using **pipenv** not **virtualenvs** for venvs. 

Try to reinstall Iris1 
Delete previous Iris1 folder, including .iris. Delete all existing virtual environments, and try install Iris1 from begin again. 

Make sure you install Iris1 right by instruction on [Iris1 wiki Linux Install](https://github.com/mozilla/iris/wiki/Setup#ubuntu-linux-instructions)

**Comment by pavelciapa** [comment] 2019-05-29 12:29
@AmbarishGK did reinstalling solved an issue?

**Comment by AmbarishGK** [comment] 2019-05-29 12:42
I think It solved the error :) Now am having this other error which isn't related to tesseract I think.
It says `AttributeError: 'module' object has no attribute 'readNet'`. Thanks @pavelciapa

**Comment by pavelciapa** [comment] 2019-05-29 12:43
@AmbarishGK share more complete log and error report here, please

**Comment by AmbarishGK** [comment] 2019-05-29 12:45
This is what am getting. 
![newerror](https://user-images.githubusercontent.com/23191860/58558144-abe46a00-823d-11e9-9b00-18bb3961a4e2.png)

**Comment by AmbarishGK** [comment] 2019-05-29 12:53
Okay I still get the error when I am running in OpenCV environment but not when I run in iris environment

**Comment by pavelciapa** [comment] 2019-05-29 12:56
@AmbarishGK I see you have Iris1 environment running, because of (iris) in the begin of terminal line.
by command `python text_recognition.py --east frozen_east_text_detection.pb ...` looks like you trying to run not related to Iris1 test case.

 To run Iris1 test you need type (while having **pipenv** running) `iris -t <name of test> `
example: `iris -t bookmark_website_from_library.py`

Available tests can be found at `iris/tests/find_toolbar/ ` dir

**Comment by pavelciapa** [comment] 2019-05-29 12:56
@AmbarishGK 
I'm sorry, but are you sure you didn't mixed issue? Tesseract among other plugins is used in Iris1 framework, which was developed to create and run test cases for Mozilla Firefox browser. Your console output looks like you run iris virt env to run text_recognition.py script which is not mentioned nowhere in Iris1.

**Comment by AmbarishGK** [comment] 2019-05-29 13:13
I was trying this [tutorial](https://www.pyimagesearch.com/2018/09/17/opencv-ocr-and-text-recognition-with-tesseract/) to detect text video. So this is the tesseract I was breaking my head over.

**Comment by pavelciapa** [comment] 2019-05-29 13:25
> 
> 
> I was trying this [tutorial](https://www.pyimagesearch.com/2018/09/17/opencv-ocr-and-text-recognition-with-tesseract/) to detect text video. So this is the tesseract I was breaking my head over.

This is not related to repository https://github.com/mozilla/iris/, where you asked a question. Please, find more appropriate issue to post a question.

As you already installed Iris, you are welcomed to try framework, create/run test case for Mozilla Firefox, and feel free to ask questions related to framework in community https://github.com/mozilla/iris

**Comment by AmbarishGK** [comment] 2019-05-31 12:58
Thanks this might be one of the really cool ways that I got into a framework :)

**Comment by pavelciapa** [comment] 2019-05-31 13:43
@AmbarishGK did you launched any of Iris1 tests? Was it successful?

**Comment by AmbarishGK** [comment] 2019-06-02 06:05
Would you call this successful?
![Screenshot_2019-06-02 Iris Control Center](https://user-images.githubusercontent.com/23191860/58757459-7d5edb80-852a-11e9-8bc4-26ac8a4c38d0.png)
How do I proceed after this?

**Comment by tracywalker** [comment] 2019-06-03 14:06
@AmbarishGK,

Yes,  to proceed, select some tests from the list of test groups, then click the blue 'Go' button.  IF successful,  that Firefox browser will close, then Firefox will reappear with the Iris logo and begin to run the tests you selected.

Good luck!

**Comment by AmbarishGK** [comment] 2019-06-05 16:26
It worked well. It did a few tests on its own. 
Thanks for the help :)
